version: '3'

services:
  api:
    build: ./dev-firebase-fuctions
    volumes:
      - ../api:/api:z
      - ../firebase.json:/api/firebase.json:z
    ports:
      - "8080:8080"
    command: yarn run start