version: '3'

services:
  proxy:
    build: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:z
      - ./proxy/log:/var/log/nginx:z
    ports:
      - "80:80"
    depends_on:
      - "web"